name: Lab 4 Helm Validation

on:
  push:
    branches:
      - main
      - lab-4

jobs:
  validate-helm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Create KinD cluster
        uses: helm/kind-action@v1.12.0
        with:
          cluster_name: lab4

      - name: Run Master Validation Script
        run: |
          chmod +x ./tests/lab4_test.sh
          ./tests/lab4_test.sh
